### ISSUE TITLE
Add reflinking mode for deduplication

### ISSUE THREAD

**Issue by lvd2** [pauldreik/rdfind#70] opened 2021-03-04 15:09 UTC
`cp` command has an option to make reflinks (for example: `cp -ra --reflink=always`) instead of hardlinks. Reflinks are only available on copy-on-write filesystems like btrfs or zfs.

Reflinking means that two files will have identical data blocks up to the moment when any of them will be changed, then copy-on-write mechanins will duplicate changed data blocks for each file.

Hardlinking is just when two filenames point to same physical file, changing one of them means changing another 'magically'

So the issue is about adding reflinking deduplication mechanism to the `rdfind`.

**Comment by thlor** [comment] 2021-05-15 12:30
This would be very useful!

**Comment by pauldreik** [comment] 2021-08-12 17:54
I agree this would be useful. I looked into how cp implemented it, a few years ago. I think it was a bit complicated. I will put this as a duplicate of https://github.com/pauldreik/rdfind/issues/17 as it is closely related.

**Closed by pauldreik** 2021-08-12 17:54 UTC
Labels: duplicate, enhancement
