### ISSUE TITLE
symlinks should point to the actual file, not other symlinks

### ISSUE THREAD

**Issue by aa755** [pauldreik/rdfind#67] opened 2021-02-07 16:23 UTC
I just used `rdfind` where I had 2 copies (say Y, Z) of a file, say X. I ended up with Y and Z becoming symlinks as expected. Y points to X as expected. But what I was not expecting is Z pointing to Y. Is there a way to run rdfind to ensure that Z points to X, i.e, all the created symlinks point to the actual files, not other symlinks?

Alternatively, is there a tool I can use to "short-circuit" my symlinks after rdfind?

**Comment by pauldreik** [comment] 2021-08-12 18:18
That is surprising. When I do the same thing, it works as intended:

```sh
#!/bin/sh

if [ -d testdir ] ; then
rm -rf testdir
fi
mkdir testdir
echo hej >testdir/X
cp testdir/X testdir/Y
cp testdir/X testdir/Z

./rdfind -makesymlinks true testdir/ 
```

gives

```text
paul@machine:~/code/rdfind$ testcases/issue67_symlinks.sh
Now scanning "testdir", found 3 files.
Now have 3 files in total.
Removed 0 files due to nonunique device and inode.
Total size is 12 bytes or 12 B
Removed 0 files due to unique sizes from list. 3 files left.
Now eliminating candidates based on first bytes: removed 0 files from list. 3 files left.
Now eliminating candidates based on last bytes: removed 0 files from list. 3 files left.
Now eliminating candidates based on sha1 checksum: removed 0 files from list. 3 files left.
It seems like you have 3 files that are not unique
Totally, 8 B can be reduced.
Now making results file results.txt
Now making symbolic links. creating 
Making 2 links.
totalt 12K
drwxr-xr-x 2 paul paul 4,0K aug 12 20:16 .
drwxr-xr-x 9 paul paul 4,0K aug 12 20:16 ..
-rw-r--r-- 1 paul paul    4 aug 12 20:16 X
lrwxrwxrwx 1 paul paul   32 aug 12 20:16 Y -> /home/paul/code/rdfind/testdir/X
lrwxrwxrwx 1 paul paul   32 aug 12 20:16 Z -> /home/paul/code/rdfind/testdir/X
paul@machine:~/code/rdfind$ 
```

**Comment by pauldreik** [comment] 2021-08-12 18:19
Please reply if you get something else than the above, and which version of rdfind you are using. Closing for now.

**Closed by pauldreik** 2021-08-12 18:19 UTC
Labels: invalid
